PRODUCT_VERSION_MAJOR = 14
PRODUCT_VERSION_MINOR = 0
PIXELAGE_VERSION = 1.0
PIXELAGE_BUILDTYPE ?= KOMUNITI

# Internal version
LINEAGE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-v$(PIXELAGE_VERSION)-$(PIXELAGE_BUILDTYPE)-$(shell date +%Y%m%d_%H%M)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-v$(PIXELAGE_VERSION)-$(PIXELAGE_BUILDTYPE)
